---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ead

<!-- badges: start -->
<!-- badges: end -->

The goal of `eadata` is to access Environment Agency data from environment.data.gov.uk website via an R package.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("aquaMetrics/eadata", dependencies = TRUE)
```
## Example

This example shows you how to get freshwater observations using R:

```{r example}
library(eadata)
## basic example to query observations from two sites
site_id <- c(
  "http://environment.data.gov.uk/ecology/site/bio/43378",
  "http://environment.data.gov.uk/ecology/site/bio/10254"
)
obs <- get_observations(site_id,
  take = 10,
  type_id =
    "http://environment.data.gov.uk/ecology/def/bio/RiverInvMetricsObservation"
)
obs[, c("date", "result.value")]
```
